import type { PublishPlatform } from "./types.js";
import { CODEX_GENERATED_MARKER } from "./platforms/codexCollection.js";

/** Platform-neutral marker for CXC-generated markdown artifacts. */
export const CXC_GENERATED_MARKER = "<!-- Generated by ContextCore AgentPublisher -->";

/** Returns generated markers accepted for backup/preview detection on a platform. */
export function generatedMarkersForPlatform(platform: PublishPlatform): string[]
{
	if (platform === "codex") return [CODEX_GENERATED_MARKER, CXC_GENERATED_MARKER];
	return [CXC_GENERATED_MARKER];
}

/** Returns the primary generated-file marker for a platform. */
export function generatedMarkerForPlatform(platform: PublishPlatform): string
{
	if (platform === "codex") return CODEX_GENERATED_MARKER;
	return CXC_GENERATED_MARKER;
}

/** Appends the platform-neutral generated marker to markdown content when absent. */
export function appendGeneratedMarker(content: string, marker = CXC_GENERATED_MARKER): string
{
	if (content.includes(marker)) return content;
	const trimmed = content.replace(/\s+$/, "");
	return `${trimmed}\n\n${marker}\n`;
}
