import { existsSync, readFileSync } from "fs";
import { dirname, join } from "path";
import type { CanonicalAgentDefinition } from "../types.js";
import { fromKnowledgeRefs } from "../canonical.js";
import { renderKnowledgeSection } from "./knowledgeFormat.js";
import { isFilePath } from "./knowledgeFormat.js";

export const CODEX_AGENTS_FILE = "AGENTS.md";
export const CODEX_AGENTS_JSON_FILE = "AGENTS.json";
export const CODEX_GENERATED_MARKER = "<!-- Generated by ContextCore AgentBuilder (platform: codex) -->";
export const CODEX_ENTRY_BEGIN_PREFIX = "<!-- CXC-CODEX-ENTRY:";
export const CODEX_ENTRY_END = "<!-- /CXC-CODEX-ENTRY -->";
export const CODEX_COLLECTION_VERSION = 2 as const;
export const CODEX_COLLECTION_GENERATOR = "ContextCore AgentBuilder";

export type CodexAgentEntry = {
	id: string;
	projectName: string;
	agentName: string;
	description: string;
	"argument-hint": string;
	tools: string[];
	agentKnowledge: string[];
	platform: "codex";
	updatedAt: string;
};

export type CodexAgentCollection = {
	version: typeof CODEX_COLLECTION_VERSION;
	platform: "codex";
	generatedBy: string;
	updatedAt: string;
	agents: CodexAgentEntry[];
};

function normalizeList(values: unknown): string[]
{
	if (!Array.isArray(values)) return [];
	return values.filter((v): v is string => typeof v === "string").map((v) => v.trim()).filter(Boolean);
}

export function slugifyId(raw: string): string
{
	const normalized = raw
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-+|-+$/g, "");
	return normalized || "codex-agent";
}

export function makeUniqueCodexEntryId(existingIds: Set<string>, base: string): string
{
	const seed = slugifyId(base);
	if (!existingIds.has(seed))
	{
		existingIds.add(seed);
		return seed;
	}
	let suffix = 2;
	while (existingIds.has(`${seed}-${suffix}`)) suffix++;
	const id = `${seed}-${suffix}`;
	existingIds.add(id);
	return id;
}

export function normalizeCodexEntry(
	input: Partial<CodexAgentEntry> & { id: string },
	fallbackProjectName: string,
): CodexAgentEntry
{
	return {
		id: slugifyId(input.id),
		projectName: input.projectName?.trim() || fallbackProjectName,
		agentName: input.agentName?.trim() || "",
		description: input.description ?? "",
		"argument-hint": input["argument-hint"] ?? "",
		tools: normalizeList(input.tools),
		agentKnowledge: normalizeList(input.agentKnowledge),
		platform: "codex",
		updatedAt: input.updatedAt?.trim() || new Date().toISOString(),
	};
}

export function toCodexCollection(agents: CodexAgentEntry[]): CodexAgentCollection
{
	return {
		version: CODEX_COLLECTION_VERSION,
		platform: "codex",
		generatedBy: CODEX_COLLECTION_GENERATOR,
		updatedAt: new Date().toISOString(),
		agents,
	};
}

export function toCodexEntryFromCanonical(def: CanonicalAgentDefinition, id: string): CodexAgentEntry
{
	return {
		id: slugifyId(id),
		projectName: def.projectName,
		agentName: def.name,
		description: def.description,
		"argument-hint": def["argument-hint"] ?? "",
		tools: def.tools ?? [],
		agentKnowledge: fromKnowledgeRefs(def.knowledge),
		platform: "codex",
		updatedAt: new Date().toISOString(),
	};
}

export function parseCodexCollectionFromJson(jsonContent: string, fallbackProjectName: string): CodexAgentCollection | null
{
	let parsed: unknown;
	try { parsed = JSON.parse(jsonContent); } catch { return null; }

	if (parsed && typeof parsed === "object" && Array.isArray((parsed as { agents?: unknown }).agents))
	{
		const obj = parsed as Record<string, unknown>;
		const usedIds = new Set<string>();
		const agents = (obj.agents as unknown[])
			.filter((c): c is Record<string, unknown> => !!c && typeof c === "object")
			.map((candidate) =>
			{
				const requested = typeof candidate.id === "string" && candidate.id.trim() !== ""
					? candidate.id
					: typeof candidate.agentName === "string" ? candidate.agentName : "codex-agent";
				const id = makeUniqueCodexEntryId(usedIds, requested);
				return normalizeCodexEntry({
					id,
					projectName: typeof candidate.projectName === "string" ? candidate.projectName : fallbackProjectName,
					agentName: typeof candidate.agentName === "string" ? candidate.agentName : "",
					description: typeof candidate.description === "string" ? candidate.description : "",
					"argument-hint": typeof candidate["argument-hint"] === "string" ? candidate["argument-hint"] : "",
					tools: normalizeList(candidate.tools),
					agentKnowledge: normalizeList(candidate.agentKnowledge),
					updatedAt: typeof candidate.updatedAt === "string" ? candidate.updatedAt : undefined,
				}, fallbackProjectName);
			});

		return {
			version: CODEX_COLLECTION_VERSION,
			platform: "codex",
			generatedBy: typeof obj.generatedBy === "string" ? obj.generatedBy : CODEX_COLLECTION_GENERATOR,
			updatedAt: typeof obj.updatedAt === "string" ? obj.updatedAt : new Date().toISOString(),
			agents,
		};
	}

	return null;
}

function parseFrontmatterValue(content: string, key: string): string
{
	const match = content.match(new RegExp(`^${key}:\\s*(.+)$`, "m"));
	return match?.[1]?.trim() ?? "";
}

function parseToolsFromBlock(content: string): string[]
{
	const match = content.match(/^tools\s*:\s*\[(.*)\]\s*$/m);
	if (!match?.[1]) return [];
	return match[1].split(",").map((t) => t.trim().replace(/^['"]|['"]$/g, "")).filter(Boolean);
}

function parseKnowledgeLinks(content: string): string[]
{
	const links: string[] = [];
	for (const match of content.matchAll(/\[[^\]]*\]\(([^)]+)\)/g))
	{
		if (match[1]) links.push(match[1].trim());
	}
	return links;
}

export function buildCodexEntryMarkdown(entry: CodexAgentEntry): string
{
	const toolsLine = entry.tools.length > 0
		? `tools: [${entry.tools.map((t) => `'${t}'`).join(", ")}]`
		: "# tools: [] # optional tool preference hints";
	const knowledgeLines = entry.agentKnowledge.length > 0
		? [
			"To get context for your task, you MUST read the following files:",
			"",
			...entry.agentKnowledge.map((k) => isFilePath(k) ? `- [${k}](${k})` : `- ${k}`),
		]
		: [];

	return [
		`${CODEX_ENTRY_BEGIN_PREFIX}${entry.id} -->`,
		"---",
		`name: ${entry.agentName}`,
		`description: ${entry.description}`,
		`argument-hint: ${entry["argument-hint"]}`,
		toolsLine,
		"---",
		"",
		...knowledgeLines,
		CODEX_ENTRY_END,
		"",
	].join("\n");
}

export function buildCodexCollectionMarkdown(collection: CodexAgentCollection): string
{
	const ordered = [...collection.agents].sort((a, b) => a.agentName.localeCompare(b.agentName));
	return [
		CODEX_GENERATED_MARKER,
		"<!-- CXC-CODEX-FORMAT: v2 -->",
		"<!-- One AGENTS.md file can contain multiple logical Codex agents. -->",
		"",
		...ordered.map(buildCodexEntryMarkdown),
	].join("\n");
}

export function parseCodexCollectionFromMarkdown(content: string, sourceName: string): CodexAgentCollection | null
{
	const lines = content.split("\n");
	const entries: CodexAgentEntry[] = [];
	const usedIds = new Set<string>();

	for (let i = 0; i < lines.length; i++)
	{
		const raw = lines[i]?.trim() ?? "";
		if (!raw.startsWith(CODEX_ENTRY_BEGIN_PREFIX) || !raw.endsWith("-->")) continue;
		const idRaw = raw.slice(CODEX_ENTRY_BEGIN_PREFIX.length, -"-->".length).trim();
		const id = makeUniqueCodexEntryId(usedIds, idRaw || "codex-agent");
		const blockLines: string[] = [];
		for (let j = i + 1; j < lines.length; j++)
		{
			const line = lines[j] ?? "";
			if (line.trim() === CODEX_ENTRY_END) { i = j; break; }
			blockLines.push(line);
		}
		const block = blockLines.join("\n");
		entries.push(normalizeCodexEntry({
			id,
			projectName: sourceName,
			agentName: parseFrontmatterValue(block, "name"),
			description: parseFrontmatterValue(block, "description"),
			"argument-hint": parseFrontmatterValue(block, "argument-hint"),
			tools: parseToolsFromBlock(block),
			agentKnowledge: parseKnowledgeLinks(block),
		}, sourceName));
	}

	if (entries.length > 0) return toCodexCollection(entries);
	return null;
}

export function loadCodexCollection(agentMdPath: string, sourceName: string): CodexAgentCollection
{
	const jsonPath = join(dirname(agentMdPath), CODEX_AGENTS_JSON_FILE);
	if (existsSync(jsonPath))
	{
		try
		{
			const parsed = parseCodexCollectionFromJson(readFileSync(jsonPath, "utf8"), sourceName);
			if (parsed) return parsed;
		} catch { /* fall through */ }
	}
	if (existsSync(agentMdPath))
	{
		try
		{
			const parsed = parseCodexCollectionFromMarkdown(readFileSync(agentMdPath, "utf8"), sourceName);
			if (parsed) return parsed;
		} catch { /* fall through */ }
	}
	return toCodexCollection([]);
}
