import { describe, expect, test } from "bun:test";
import { dirname, join } from "path";
import { tmpdir } from "os";
import { mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync, unlinkSync, writeFileSync } from "fs";
import { AgentBuilder, type CreateAgentInput } from "../AgentBuilder.js";
import type { MachineConfig } from "../../types.js";

function buildTestMachine(
	sourcePath: string,
	options?: { codexAgentPath?: string; codexAgentPaths?: string[]; agentPath?: string }
): MachineConfig
{
	return {
		machine: "TEST-HOST",
		harnesses: {},
		dataSources: {
			"agent-test": [
				{
					path: sourcePath,
					name: "Test Project",
					type: "Repo",
					purpose: "AgentBuilder",
					agentPath: options?.agentPath,
					codexAgentPath: options?.codexAgentPath,
					codexAgentPaths: options?.codexAgentPaths,
				},
			],
		},
	};
}

function codexInput(agentName: string, extra?: Partial<CreateAgentInput>): CreateAgentInput
{
	return {
		projectName: "Test Project",
		agentName,
		description: `${agentName} worker`,
		"argument-hint": `Implement tasks for ${agentName}`,
		tools: ["read", "edit"],
		agentKnowledge: ["docs/architecture.md", `rules/${agentName}.md`],
		platform: "codex",
		...extra,
	};
}

describe("AgentBuilder codex platform (multi-entry collections)", () =>
{
	test("create(platform=codex) writes AGENTS.md + AGENTS.json(v2 agents[])", () =>
	{
		const tempRoot = mkdtempSync(join(tmpdir(), "agentbuilder-codex-create-"));
		try
		{
			const sourcePath = join(tempRoot, "repo");
			mkdirSync(sourcePath, { recursive: true });
			const builder = new AgentBuilder(buildTestMachine(sourcePath));

			const created = builder.create(codexInput("codex-worker"));
			expect(created.created).toBe(true);
			expect(created.path.endsWith("AGENTS.md")).toBe(true);
			expect(created.codexEntryId).toBe("codex-worker");

			const mdContent = readFileSync(created.path, "utf8");
			expect(mdContent).toContain("Generated by ContextCore AgentBuilder (platform: codex)");
			expect(mdContent).toContain("CXC-CODEX-ENTRY:codex-worker");
			expect(mdContent).toContain("name: codex-worker");

			const jsonPath = join(dirname(created.path), "AGENTS.json");
			const json = JSON.parse(readFileSync(jsonPath, "utf8")) as { version?: number; agents?: Array<{ id?: string; agentName?: string }> };
			expect(json.version).toBe(2);
			expect(Array.isArray(json.agents)).toBe(true);
			expect(json.agents?.length).toBe(1);
			expect(json.agents?.[0]?.id).toBe("codex-worker");
			expect(json.agents?.[0]?.agentName).toBe("codex-worker");
		}
		finally
		{
			rmSync(tempRoot, { recursive: true, force: true });
		}
	});

	test("create(platform=codex) upserts one entry and preserves siblings in same AGENTS files", () =>
	{
		const tempRoot = mkdtempSync(join(tmpdir(), "agentbuilder-codex-upsert-"));
		try
		{
			const sourcePath = join(tempRoot, "repo");
			mkdirSync(sourcePath, { recursive: true });
			const builder = new AgentBuilder(buildTestMachine(sourcePath));

			const first = builder.create(codexInput("knk-home"));
			const second = builder.create(codexInput("biome-worker"));
			expect(first.codexEntryId).toBe("knk-home");
			expect(second.codexEntryId).toBe("biome-worker");

			const listed = builder.list();
			expect(listed.totalAgents).toBe(2);
			expect(listed.agents.map((a) => a.name).sort()).toEqual(["biome-worker", "knk-home"]);
			expect(new Set(listed.agents.map((a) => a.path)).size).toBe(1);
			expect(new Set(listed.agents.map((a) => a.codexEntryId)).size).toBe(2);

			// Update one entry only
			builder.create(codexInput("knk-home", {
				codexEntryId: "knk-home",
				description: "Updated KNK Home description",
			}));

			const afterUpdate = builder.list();
			expect(afterUpdate.totalAgents).toBe(2);
			const updated = afterUpdate.agents.find((a) => a.codexEntryId === "knk-home");
			const untouched = afterUpdate.agents.find((a) => a.codexEntryId === "biome-worker");
			expect(updated?.description).toBe("Updated KNK Home description");
			expect(untouched?.description).toBe("biome-worker worker");
		}
		finally
		{
			rmSync(tempRoot, { recursive: true, force: true });
		}
	});

	test("getAgent() requires codexEntryId when AGENTS contains multiple entries", () =>
	{
		const tempRoot = mkdtempSync(join(tmpdir(), "agentbuilder-codex-get-"));
		try
		{
			const sourcePath = join(tempRoot, "repo");
			mkdirSync(sourcePath, { recursive: true });
			const builder = new AgentBuilder(buildTestMachine(sourcePath));

			const a = builder.create(codexInput("knk-home"));
			builder.create(codexInput("biome-worker"));

			expect(() => builder.getAgent(a.path)).toThrow();

			const selected = builder.getAgent(a.path, "knk-home").agent;
			expect(selected.platform).toBe("codex");
			expect(selected.codexEntryId).toBe("knk-home");
			expect(selected.agentName).toBe("knk-home");
			expect(selected.fromJson).toBe(true);
		}
		finally
		{
			rmSync(tempRoot, { recursive: true, force: true });
		}
	});

	test("getAgent() falls back to markdown and still resolves codexEntryId", () =>
	{
		const tempRoot = mkdtempSync(join(tmpdir(), "agentbuilder-codex-markdown-fallback-"));
		try
		{
			const sourcePath = join(tempRoot, "repo");
			mkdirSync(sourcePath, { recursive: true });
			const builder = new AgentBuilder(buildTestMachine(sourcePath));

			const a = builder.create(codexInput("knk-home"));
			builder.create(codexInput("biome-worker"));
			unlinkSync(join(dirname(a.path), "AGENTS.json"));

			const selected = builder.getAgent(a.path, "biome-worker").agent;
			expect(selected.fromJson).toBe(false);
			expect(selected.codexEntryId).toBe("biome-worker");
			expect(selected.agentName).toBe("biome-worker");
			expect(selected.platform).toBe("codex");
		}
		finally
		{
			rmSync(tempRoot, { recursive: true, force: true });
		}
	});

	test("create(platform=codex) backs up existing unmanaged AGENTS.md before overwrite", () =>
	{
		const tempRoot = mkdtempSync(join(tmpdir(), "agentbuilder-codex-backup-"));
		try
		{
			const sourcePath = join(tempRoot, "repo");
			mkdirSync(sourcePath, { recursive: true });
			const agentsPath = join(sourcePath, "AGENTS.md");
			const unmanaged = "Manual AGENTS instructions\nDo not lose me.\n";
			writeFileSync(agentsPath, unmanaged, "utf8");

			const builder = new AgentBuilder(buildTestMachine(sourcePath));
			builder.create(codexInput("knk-home"));

			const backups = readdirSync(sourcePath).filter((name) => name.startsWith("AGENTS.md.bak."));
			expect(backups.length).toBe(1);
			const backupContent = readFileSync(join(sourcePath, backups[0]!), "utf8");
			expect(backupContent).toBe(unmanaged);
		}
		finally
		{
			rmSync(tempRoot, { recursive: true, force: true });
		}
	});

	test("create(platform=codex) infers target from agentPath when it points to .github/agents", () =>
	{
		const tempRoot = mkdtempSync(join(tmpdir(), "agentbuilder-codex-infer-"));
		try
		{
			const repoRoot = join(tempRoot, "repo");
			const githubAgents = join(repoRoot, ".github", "agents");
			mkdirSync(githubAgents, { recursive: true });

			const builder = new AgentBuilder(buildTestMachine(repoRoot, { agentPath: githubAgents }));
			const created = builder.create(codexInput("knk-home"));

			expect(created.path).toBe(join(repoRoot, "AGENTS.md"));
			expect(readFileSync(created.path, "utf8")).toContain("Generated by ContextCore AgentBuilder");
		}
		finally
		{
			rmSync(tempRoot, { recursive: true, force: true });
		}
	});

	test("create(platform=codex) supports explicit codexDirectory from codexAgentPaths", () =>
	{
		const tempRoot = mkdtempSync(join(tmpdir(), "agentbuilder-codex-dirs-"));
		try
		{
			const sourcePath = join(tempRoot, "repo");
			const dirA = join(sourcePath, "apps", "a");
			const dirB = join(sourcePath, "apps", "b");
			mkdirSync(dirA, { recursive: true });
			mkdirSync(dirB, { recursive: true });

			const builder = new AgentBuilder(buildTestMachine(sourcePath, { codexAgentPaths: [dirA, dirB] }));
			const created = builder.create(codexInput("knk-home", { codexDirectory: dirB }));
			expect(created.path).toBe(join(dirB, "AGENTS.md"));
		}
		finally
		{
			rmSync(tempRoot, { recursive: true, force: true });
		}
	});

	test("create(platform=codex) requires codexDirectory when multiple codexAgentPaths are configured", () =>
	{
		const tempRoot = mkdtempSync(join(tmpdir(), "agentbuilder-codex-dirs-required-"));
		try
		{
			const sourcePath = join(tempRoot, "repo");
			const dirA = join(sourcePath, "apps", "a");
			const dirB = join(sourcePath, "apps", "b");
			mkdirSync(dirA, { recursive: true });
			mkdirSync(dirB, { recursive: true });

			const builder = new AgentBuilder(buildTestMachine(sourcePath, { codexAgentPaths: [dirA, dirB] }));
			expect(() => builder.create(codexInput("knk-home"))).toThrow();
		}
		finally
		{
			rmSync(tempRoot, { recursive: true, force: true });
		}
	});

	test("legacy single-entry AGENTS.json remains readable as one logical Codex agent", async () =>
	{
		const tempRoot = mkdtempSync(join(tmpdir(), "agentbuilder-codex-legacy-v1-"));
		try
		{
			const sourcePath = join(tempRoot, "repo");
			mkdirSync(sourcePath, { recursive: true });

			const agentsMdPath = join(sourcePath, "AGENTS.md");
			const agentsJsonPath = join(sourcePath, "AGENTS.json");
			writeFileSync(agentsMdPath, [
				"---",
				"name: legacy-home",
				"description: Legacy codex entry",
				"argument-hint: Handle legacy tasks",
				"---",
				"",
				"- [docs/legacy.md](docs/legacy.md)",
				"",
			].join("\n"), "utf8");
			writeFileSync(agentsJsonPath, JSON.stringify({
				projectName: "Test Project",
				agentName: "legacy-home",
				description: "Legacy codex entry",
				"argument-hint": "Handle legacy tasks",
				tools: ["read"],
				agentKnowledge: ["docs/legacy.md"],
				platform: "codex",
			}, null, 2), "utf8");

			const builder = new AgentBuilder(buildTestMachine(sourcePath));
			await builder.index();

			const listed = builder.list();
			expect(listed.totalAgents).toBe(1);
			expect(listed.agents[0]?.name).toBe("legacy-home");
			expect(listed.agents[0]?.codexEntryId).toBe("legacy-home");

			const loaded = builder.getAgent(agentsMdPath).agent;
			expect(loaded.fromJson).toBe(true);
			expect(loaded.platform).toBe("codex");
			expect(loaded.codexEntryId).toBe("legacy-home");
			expect(loaded.agentName).toBe("legacy-home");
		}
		finally
		{
			rmSync(tempRoot, { recursive: true, force: true });
		}
	});

	test("legacy Codex agents with missing/duplicate ids are recovered deterministically", async () =>
	{
		const tempRoot = mkdtempSync(join(tmpdir(), "agentbuilder-codex-legacy-ids-"));
		try
		{
			const sourcePath = join(tempRoot, "repo");
			mkdirSync(sourcePath, { recursive: true });

			const agentsMdPath = join(sourcePath, "AGENTS.md");
			const agentsJsonPath = join(sourcePath, "AGENTS.json");
			writeFileSync(agentsMdPath, "<!-- placeholder -->\n", "utf8");
			writeFileSync(agentsJsonPath, JSON.stringify({
				version: 2,
				platform: "codex",
				agents: [
					{
						id: "dup",
						projectName: "Test Project",
						agentName: "first",
						description: "one",
						"argument-hint": "h1",
						tools: [],
						agentKnowledge: [],
					},
					{
						id: "dup",
						projectName: "Test Project",
						agentName: "second",
						description: "two",
						"argument-hint": "h2",
						tools: [],
						agentKnowledge: [],
					},
					{
						projectName: "Test Project",
						agentName: "Third Agent",
						description: "three",
						"argument-hint": "h3",
						tools: [],
						agentKnowledge: [],
					},
				],
			}, null, 2), "utf8");

			const builder = new AgentBuilder(buildTestMachine(sourcePath));
			await builder.index();

			const listed = builder.list();
			expect(listed.totalAgents).toBe(3);

			const ids = listed.agents.map((entry) => entry.codexEntryId).sort();
			expect(ids).toEqual(["dup", "dup-2", "third-agent"]);

			const selected = builder.getAgent(agentsMdPath, "dup-2").agent;
			expect(selected.agentName).toBe("second");
		}
		finally
		{
			rmSync(tempRoot, { recursive: true, force: true });
		}
	});

	test("github and claude create/list/get flows remain unchanged", async () =>
	{
		const tempRoot = mkdtempSync(join(tmpdir(), "agentbuilder-platform-regression-"));
		try
		{
			const repoRoot = join(tempRoot, "repo");
			const githubAgents = join(repoRoot, ".github", "agents");
			mkdirSync(githubAgents, { recursive: true });

			const builder = new AgentBuilder(buildTestMachine(repoRoot, { agentPath: githubAgents }));

			const githubCreated = builder.create({
				projectName: "Test Project",
				agentName: "gh-worker",
				description: "GitHub worker",
				"argument-hint": "Handle GitHub tasks",
				tools: ["read"],
				agentKnowledge: ["docs/gh.md"],
				platform: "github",
			});
			const claudeCreated = builder.create({
				projectName: "Test Project",
				agentName: "claude-worker",
				description: "Claude worker",
				"argument-hint": "Handle Claude tasks",
				tools: ["read"],
				agentKnowledge: ["docs/claude.md"],
				platform: "claude",
			});

			expect(githubCreated.path).toBe(join(githubAgents, "gh-worker.agent.md"));
			expect(claudeCreated.path).toBe(join(repoRoot, ".claude", "agents", "claude-worker.md"));
			expect(readFileSync(join(githubAgents, "gh-worker.agent.json"), "utf8")).toContain("\"platform\": \"github\"");
			expect(readFileSync(join(repoRoot, ".claude", "agents", "claude-worker.json"), "utf8")).toContain("\"platform\": \"claude\"");

			await builder.index();
			const listed = builder.list();
			expect(listed.totalAgents).toBe(2);
			expect(listed.agents.find((entry) => entry.name === "gh-worker")?.platform).toBe("github");
			expect(listed.agents.find((entry) => entry.name === "claude-worker")?.platform).toBe("claude");

			const githubAgent = builder.getAgent(githubCreated.path).agent;
			const claudeAgent = builder.getAgent(claudeCreated.path).agent;
			expect(githubAgent.platform).toBe("github");
			expect(claudeAgent.platform).toBe("claude");
		}
		finally
		{
			rmSync(tempRoot, { recursive: true, force: true });
		}
	});
});
