/**
 * ScopeEntry represents a saved project scope for the visualizer New View dialog.
 * Stored in .settings/scopes.json.
 */

export type ScopeProject = {
  /** Harness name (e.g. ClaudeCode, Cursor, VSCode). */
  harness: string;
  /** Project name within the harness. */
  project: string;
};

export type ScopeEntry = {
  /** Unique scope identifier (UUID generated by client). */
  id: string;
  /** Display name shown on the scope button. */
  name: string;
  /** Scope emoji icon. */
  emoji: string;
  /** Scope color in #RRGGBB format. */
  color: string;
  /** Selected projects belonging to this scope. */
  projectIds: ScopeProject[];
};
