import { describe, expect, test } from "bun:test";
import { dirname, join } from "path";
import { tmpdir } from "os";
import { mkdtempSync, mkdirSync, readFileSync, rmSync } from "fs";
import { AgentPublisherCopilot, renderAgentMarkdown } from "../platforms/AgentPublisherCopilot.js";
import { AgentPublisherClaude } from "../platforms/AgentPublisherClaude.js";
import { AgentPublisherCodex } from "../platforms/AgentPublisherCodex.js";
import { toCanonicalAgentDefinition } from "../canonical.js";
import { AgentBuilder } from "../../agentBuilder/AgentBuilder.js";
import { CanonicalAgentStore } from "../CanonicalAgentStore.js";
import type { MachineConfig } from "../../types.js";

function canonical(overrides?: Partial<ReturnType<typeof toCanonicalAgentDefinition>>)
{
	return {
		...toCanonicalAgentDefinition({
			projectName: "Test Project",
			agentName: "worker",
			description: "Worker agent",
			"argument-hint": "Do work",
			tools: ["read", "edit"],
			agentKnowledge: ["docs/architecture.md", "Always verify tests"],
		}),
		...overrides,
	};
}

describe("platform publishers", () =>
{
	test("Copilot render matches legacy github frontmatter shape", () =>
	{
		const def = canonical();
		const md = renderAgentMarkdown(def);
		expect(md).toContain("name: worker");
		expect(md).toContain("argument-hint: Do work");
		expect(md).toContain("[docs/architecture.md](docs/architecture.md)");
		expect(md).toContain("- Always verify tests");
		expect(md).toContain("Generated by ContextCore AgentPublisher");
	});

	test("Claude publisher renders file and text knowledge", () =>
	{
		const publisher = new AgentPublisherClaude();
		const artifacts = publisher.render(canonical(), {
			platform: "claude",
			artifactKind: "agent",
			outputDir: "/tmp/.claude/agents",
		});
		expect(artifacts[0]?.content).toContain("[architecture.md](docs/architecture.md)");
		expect(artifacts[0]?.content).toContain("- Always verify tests");
	});

	test("Codex publisher upserts collection entries", () =>
	{
		const tempRoot = mkdtempSync(join(tmpdir(), "publisher-codex-"));
		try
		{
			const outputDir = join(tempRoot, "repo");
			mkdirSync(outputDir, { recursive: true });
			const publisher = new AgentPublisherCodex();
			const def = canonical();
			const artifacts = publisher.render(def, {
				platform: "codex",
				artifactKind: "agent",
				outputDir,
			});
			const mdPath = artifacts.find((a) => a.absolutePath.endsWith("AGENTS.md"))!.absolutePath;
			publisher.materializeArtifacts(artifacts);
			const first = readFileSync(mdPath, "utf8");
			expect(first).toContain(`CXC-CODEX-ENTRY:${def.id}`);

			const secondArtifacts = publisher.render(canonical({ name: "other", id: "other" }), {
				platform: "codex",
				artifactKind: "agent",
				outputDir,
			});
			publisher.materializeArtifacts(secondArtifacts);
			const second = readFileSync(mdPath, "utf8");
			expect(second).toContain(`CXC-CODEX-ENTRY:${def.id}`);
			expect(second).toContain("CXC-CODEX-ENTRY:other");
		}
		finally
		{
			rmSync(tempRoot, { recursive: true, force: true });
		}
	});

	test("skill paths per platform", () =>
	{
		const copilot = new AgentPublisherCopilot();
		const claude = new AgentPublisherClaude();
		const codex = new AgentPublisherCodex();
		const def = canonical({ kind: "skill" });
		const out = join("/repo", "root");
		const copilotPath = copilot.render(def, { platform: "copilot", artifactKind: "skill", outputDir: out })[0]!.absolutePath.replace(/\\/g, "/");
		const claudePath = claude.render(def, { platform: "claude", artifactKind: "skill", outputDir: out })[0]!.absolutePath.replace(/\\/g, "/");
		const codexPath = codex.render(def, { platform: "codex", artifactKind: "skill", outputDir: out })[0]!.absolutePath.replace(/\\/g, "/");
		expect(copilotPath).toContain("/.github/skills/");
		expect(claudePath).toContain("/.claude/skills/");
		expect(codexPath).toContain("/.agents/skills/");
	});

	test("AgentBuilder canonical-only create persists definition", () =>
	{
		const tempRoot = mkdtempSync(join(tmpdir(), "ab-canonical-"));
		try
		{
			const sourcePath = join(tempRoot, "repo");
			const storage = join(tempRoot, "storage");
			mkdirSync(sourcePath, { recursive: true });
			const machine: MachineConfig = {
				machine: "T",
				harnesses: {},
				dataSources: {
					t: [{
						path: sourcePath,
						name: "Test Project",
						type: "Repo",
						purpose: "AgentBuilder",
					}],
				},
			};
			const store = new CanonicalAgentStore(storage);
			store.load();
			const builder = new AgentBuilder(machine, store);
			const result = builder.create({
				projectName: "Test Project",
				agentName: "worker",
				description: "d",
				"argument-hint": "h",
				agentKnowledge: [],
			});
			expect(result.canonicalId).toBeDefined();
			expect(result.canonicalDefinition?.name).toBe("worker");
			expect(result.persisted).toBe(true);
			expect(result.path).toBeUndefined();
			const reloaded = new CanonicalAgentStore(storage);
			reloaded.load();
			expect(reloaded.get(result.canonicalId!)?.name).toBe("worker");
		}
		finally
		{
			rmSync(tempRoot, { recursive: true, force: true });
		}
	});
});
